### ISSUE TITLE
supported entry types needs to be context aware

### ISSUE THREAD

**Issue by cvazac** [w3c/longtasks#57] opened 2019-01-16 18:45 UTC
Companion issue to https://github.com/w3c/performance-timeline/issues/113.

[Relevant bits](https://github.com/w3c/longtasks/blob/5302ce6c1cd27b4a7d4a90f5325a58a8223cb91c/index.bs#L33).

**Comment by toddreifsteck** [comment] 2019-08-01 18:53
Per call on 8/1, this may be fixed the the registry. @npm1 , could you confirm?

**Comment by yoavweiss** [comment] 2019-08-01 18:55
Confirmed that the issue is resolved. Closing

**Closed by yoavweiss** 2019-08-01 18:55 UTC
